services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: bible-books-tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
